import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Favicon from '@/app/assets/brainwave-symbol.svg'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Brainwave",
  description: "Generated by create next app",
  /* icons: {
    icon: Favicon,
  } */
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
